### ISSUE TITLE
Consider allowing some leniency in parsing

### ISSUE THREAD

**Issue by gpdf** [pyvirtobs/pyvo#104]
Currently when `pyvo.dal.AsyncTAPJob` parses the status of a job, if an invalid date is returned that cannot be parsed by the `XSInDate` function, an exception is thrown that prevents the software from functioning altogether.

While it is perfectly justifiable to reject invalid inputs - and doing so eventually produces back pressure against the data publisher involved - it also is a valid design consideration for a library provider to be lenient where it does not significantly affect functionality.  (As in the case of the job status dates for async TAP jobs, which are essentially purely informational.)

Feel free to come down on the side of strict parsing; I just want to trigger some formal thought about whether this is in fact the `pyvo` policy.

(In the mean time, I've also filed a ticket against the data publisher whose service bug triggered my noticing this.)

**Comment by funbaker** [comment]
Thank you for also reporting to the data publisher.

Just to be sure that this is no "real" bug: Can you post the errornous datetime string?

I'm thinking about introducing a ``pedantic`` parameter for uws parsing together with warnings, like it is already done in ``astropy.io.votable``.

**Comment by gpdf** [comment]
My apologies for the late reply.

There were two problems, in the end.  The first was that the `uws:destruction` date was reported as "2038-0-0T00:00:00Z", a totally invalid date even at face value.  This was the trigger for my report above.

The other, which was revealed after the first bug was fixed by the publisher, was that the job start/end times were reported as, e.g., "2018-9-13T9:27:45Z", instead of the ISO standard "2018-09-13T09:27:45Z".

The publisher has fixed both of these problems in the mean time and will soon deploy the fixes to production.

**Comment by funbaker** [comment]
I think i also fixed this by being less strict, if not, feel free to re-open
