### ISSUE TITLE
service.describe() throws because of spelling error

### ISSUE THREAD

**Issue by cbanek** [pyvirtobs/pyvo#105]
There's a spelling error in tapregext.py of fornat instead of format.  Subtle.

When I tried to run the following code:

import pyvo
service = pyvo.dal.TAPService('http://gea.esac.esa.int/tap-server/tap')
service.describe()

Output:
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): gea.esac.esa.int:80
DEBUG:urllib3.connectionpool:http://gea.esac.esa.int:80 "GET /tap-server/tap/tables HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): gea.esac.esa.int:80
DEBUG:urllib3.connectionpool:http://gea.esac.esa.int:80 "GET /tap-server/tap/capabilities HTTP/1.1" 200 None
Capability ivo://ivoa.net/std/TAP

Interface vs:ParamHTTP
    http://gea.esac.esa.int/tap-server/tap/tap

Language ADQL
Output format application/x-votable+xml
    Also available as votable

Output format application/x-votable+xml
    Also available as votable_plain

Output format text/csv
    Also available as csv

Output format application/json
    Also available as json

Output format application/fits
    Also available as fits

Output format text/xml
    Also available as votable_plain_conesearch

Upload method supported
    ivo://ivoa.org/tap/uploadmethods#inline

Upload method supported
    ivo://ivoa.org/tap/uploadmethods#http

Upload method supported
    ivo://ivoa.org/tap/uploadmethods#ftp

Upload method supported
    ivo://ivoa.net/std/TAPRegExt#upload-inline

Upload method supported
    ivo://ivoa.net/std/TAPRegExt#upload-http

Upload method supported
    ivo://ivoa.net/std/TAPRegExt#upload-ftp

Time a job is kept (in seconds)
    Default 259200
Traceback (most recent call last):
  File "./vo2oracle.py", line 11, in <module>
    service.describe()
  File "/home/cbanek/env/lib/python3.6/site-packages/pyvo/dal/tap.py", line 328, in describe
    cap.describe()
  File "/home/cbanek/env/lib/python3.6/site-packages/pyvo/io/vosi/tapregext.py", line 401, in describe
    print(indent("Maximum {}".fornat(self.retentionperiod.hard)))
AttributeError: 'str' object has no attribute 'fornat'

Fix is incoming in a PR.

**Comment by funbaker** [comment]
Thank you. Somewhere i fixed this, but it seems it landed in some `git stash` kind of black hole.

Please do the PR against the v0.9.x branch.
