### ISSUE TITLE
Please remove "v9.0" tag on github

### ISSUE THREAD

**Issue by olebole** [pyvirtobs/pyvo#110]
On Debian, we search for the latest version of the package for the largest tag number on github. Since there is now a (probably errornous) ['v9.0'](https://github.com/pyvirtobs/pyvo/releases/tag/v9.0) tag, this system is not usable anymore, since we always get a ["A new upstream version is available: 9.0"](https://tracker.debian.org/pkg/pyvo) message, and new versions need to be queried and downloaded manually.

Unless this tag serves some purpose in the repository, would you consider removing it? That would make our life easier ;-)

Thank you!

Best

Ole

**Comment by msdemlei** [comment]
It's gone.  Sorry about that one.
