### ISSUE TITLE
cachedataset fails if subdirectories don't exist

### ISSUE THREAD

**Issue by keflavich** [pyvirtobs/pyvo#46]
If you try to retrieve data that is in a subdirectory, retrieval will fail, for example with Spitzer data:

`IOError: [Errno 2] No such file or directory: 'skyview_images/r13368832/ch4/pbcd/SPITZER_I4_13368832_0000_6_E8709940_maic.fits.fits'`

```
zz = coordinates.Galactic(0*u.deg,0*u.deg)
results = spitzer.search(pos=(zz.icrs.ra.deg,zz.icrs.dec.deg), size=0.1)
os.mkdir('skyview_images/') # this is wrong but I was following an example...
for a in results:
    if a['wavelength'] == 'IRAC 8.0um':
        a.cachedataset(dir='skyview_images/')
```

**Comment by funbaker** [comment]
fixed in https://github.com/pyvirtobs/pyvo/commit/5753d801e2542bdec6af4a4b484da13ac19f0b99
