### ISSUE TITLE
Don't run 2to3 for Python 3

### ISSUE THREAD

**Issue by cdeil** [pyvirtobs/pyvo#51]
As mentioned in https://github.com/astropy/package-template/pull/93 it would be nice if Astropy and all affiliated packages worked with a single Python 2 / 3 codebase.

This is usually not hard to achieve ... set `use_2to3=False` in `setup.py` and then once run `2to3` on your package and manually go through the suggested changes to see which ones make sense.

**Comment by funbaker** [comment]
f4eeef8ef7181a5592bfc7b2e580b7a9f84e39a1 added usage of `six`
and
91de61b9653a7566e1a5398369a4f6df0f86c17a updated to the latest `astropy` template (with use_2to3=False)
