### ISSUE TITLE
Provide better visibility of the size of download sizes

### ISSUE THREAD

**Issue by RayPlante** [pyvirtobs/pyvo#57]
As part of #29, @jimaples suggested adding a `verbose` parameter to `cachedataset()` to print download progress.  We can also provide better visibility for this information prior to calling this function, all with the idea of letting the user what they are in for when downloading large files.  As this is a comparable amount of work to the original issue, I'm splitting this one off.  

The filesize is returned as metadata in the initial query.  Sometimes this value may not be provided if the file is being generated on the fly (e.g. via cutout).

**Comment by funbaker** [comment]
SIA already had filesize property, added it for SSA in https://github.com/pyvirtobs/pyvo/commit/160bb32df6ee221f45717511283608669c339bec
