### ISSUE TITLE
Docstrings - specify units / use astropy.units?

### ISSUE THREAD

**Issue by keflavich** [pyvirtobs/pyvo#7]
In some of the docstrings, "size" is requested without reference to units, e.g. `imagesearch`:

```
   *pos*:  a 2-element seqence giving the ICRS RA and DEC in decimal degrees
   *size*: a floating point number or a 2-element tuple giving the size
             of the rectangular region around pos to search for images.
```

First, units should be specified everywhere (minor but important point).

Second, though - in astroquery, we've decided that all coordinate-based requests need to either be:
1. a string that can unambiguously be parsed into a coordinate (i.e., there is no ambiguity between "galactic" or "fk5"
2. an astropy.coordinates instance

I think that approach would be useful for pyvo as well, particularly since it will allow us to present a common user interface between astroquery and pyvo.  Achieving that broad goal will take a bit more work, but at least accepting `astropy.coordinates` as input is a good first step.

**Comment by funbaker** [comment]
Input parameters are astropy integrated, where possible
