### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by smoh** [pyvirtobs/pyvo#81]
Hi,

`pip install pyvo` in fresh conda env for python=3.5 or 2.7 fails with the following
```
$ pip install pyvo
Collecting pyvo
  Using cached pyvo-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qs/084gcc8907s6zmz_8qbj4qd40000gn/T/pip-build-ijlobmbe/pyvo/setup.py", line 17, in <module>
        from astropy_helpers.setup_helpers import (
    ImportError: No module named 'astropy_helpers'

    ----------------------------------------
```
I'm wondering if I could get some help.

**Comment by funbaker** [comment]
Hello,

please try installing `astropy-helpers` before installing `pyvo`.

**Comment by smoh** [comment]
Yep, that does solve the problem. Thanks. I just thought this is something to be taken care of in the setup.py.

**Comment by funbaker** [comment]
It is. It is already in the master branch and will be included in the next release.
