### ISSUE TITLE
Exception while parsing /tables response of TAP Service

### ISSUE THREAD

**Issue by smoh** [pyvirtobs/pyvo#82]
I'm redirecting an issue regarding `tables` property of `TAPService` class from astropy to here.
(https://github.com/astropy/astropy/issues/5936)

https://gist.github.com/anonymous/0a7383ed6a2f815cbfd16204bda8bc20

The bug is that while parsing the list of tables from Simbad TAP Service, it will complain `DOUBLE` as unknown datatype, and while raising this error, it will raise another AttributeError because the on-the-fly class `_field` (https://github.com/pyvirtobs/pyvo/blob/master/pyvo/tools/vosi.py#L257-L266) has no ID attribute. This seems to happen for other TAP Services as well.

**Comment by msdemlei** [comment]
Yes, that's a bug.  The class should be prepared to see any of VODataService's vs:TAPTYPE values here (that's  "BOOLEAN" | "SMALLINT" | "INTEGER" | "BIGINT" | "REAL" | "DOUBLE" | "TIMESTAMP" | "CHAR" | "VARCHAR" | "BINARY" | "VARBINARY" | "POINT" | "REGION" | "CLOB" | "BLOB" in version 1.1, as well
as the values from vs:VOTableType (that are totally ok in a tableSet; that's "boolean" | "bit" | "unsignedByte" | "short" | "int" | "long" | "char" | "unicodeChar" | "float" | "double" | "floatComplex" | "doubleComplex"), and finally vs:SimpleDataType (which is "integer" | "real" | "complex" | "boolean" | "char" | "string").

Sorry for the confusion; it seemed like a necessity at the time, and it 
might still be (though I admit it might be a smart move to require TAP data
types in TAP service's tableSets; not quite sure).

**Comment by funbaker** [comment]
Sorry for the late answer - I got to rework the XML stuff in pyvo.tools anyway, but this will take some time.

**Comment by funbaker** [comment]
Fixed with https://github.com/pyvirtobs/pyvo/commit/d71dae6d4e0bb71683a69bdef9f73276197dbc63
