### ISSUE TITLE
pyvo 0.6.0 shows up as pyvo 0.5.2

### ISSUE THREAD

**Issue by lupinix** [pyvirtobs/pyvo#83]
When starting to update Fedora's pyvo package, I recognized that our dependency generator created output like "python3dist(pyvo) = 0.5.2". When looking into the source I found, that at least setup.cfg still lists version 0.5.2. Are there more locations where the version is coded in?

Greetings,
Christian

**Comment by funbaker** [comment]
Which package manager is that?

**Comment by lupinix** [comment]
RPM package format. Fedora packaging stuff nowadays also analyzes the package content to find the generic module names, not only our package spec.

**Comment by funbaker** [comment]
I'm not sure what happened here.

@sladen can you help with that?

**Comment by lupinix** [comment]
I'll check now whether the latest commit changing setup.cfg fixes it.

**Comment by lupinix** [comment]
Fixed with commit 3fa56a6406ddd7aee0e735aa5ba8b02d11a48780
