### ISSUE TITLE
pyvo.dal.TAPService.submit_job fails on jobs with a NULL destruction time

### ISSUE THREAD

**Issue by almicol** [pyvirtobs/pyvo#89]
When I do:
import numpy
import astropy
import pyvo as vo
url = "http://aspint:8889/esotap"
service = vo.dal.TAPService(url)
query = "select top 1 target_name from ivoa.ObsCore"
job = service.submit_job(query)

I get the error: ValueError: Input values did not match the format class isot

The reason for that is that pyvo expects the Destruction Time to be set,
while it shouldn't. In the my esotap/async case, the distruction time is not set.

Because of that the input value to the _get_time_fmt function is an empty string, and that causes the format failure.

The esotap server indeed returns:
&lt;destruction xsi:nil="true"/&gt;
which is perfectly legitimate according to the section "2.1.5. Destruction Time"
of the UWS standard:
http://www.ivoa.net/documents/UWS/20161024/REC-UWS-1.1-20161024.html

I have installed: pyvo 0.6.1, astropy 2.0.1, and numpy 1.8.3 on a Mac El Captain.

Full traceback follows.
Thanks,
Alberto

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-5aaedbbc967d> in <module>()
----> 1 job = service.submit_job(query)

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/dal/tap.py in submit_job(self, query, language, maxrec, uploads)
    257         """
    258         return AsyncTAPJob.create(
--> 259             self.baseurl, query, language, maxrec, uploads)
    260 
    261     def create_query(

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/dal/tap.py in create(cls, baseurl, query, language, maxrec, uploads, **keywords)
    320             uploads=uploads, **keywords)
    321         response = query.submit()
--> 322         job = cls(response.url)
    323         return job
    324 

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/dal/tap.py in __init__(self, url)
    333         """
    334         self._url = url
--> 335         self._update()
    336 
    337     def __enter__(self):

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/dal/tap.py in _update(self, wait_for_statechange)
    368         response.raw.read = partial(response.raw.read, decode_content=True)
    369 
--> 370         self._job.update(uws.parse_job(response.raw))
    371 
    372     @property

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/tools/uws.py in parse_job(stream)
     57 def parse_job(stream):
     58         parser = _JobParser()
---> 59         parser.parse(stream)
     60         return parser.getResult()

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/tools/plainxml.py in parse(self, stream)
    221 
    222         def parse(self, stream):
--> 223                 xml.sax.parse(stream, self)
    224                 return self
    225 

/Users/amicol/anaconda/lib/python3.6/xml/sax/__init__.py in parse(source, handler, errorHandler)
     31     parser.setContentHandler(handler)
     32     parser.setErrorHandler(errorHandler)
---> 33     parser.parse(source)
     34 
     35 def parseString(string, handler, errorHandler=ErrorHandler()):

/Users/amicol/anaconda/lib/python3.6/xml/sax/expatreader.py in parse(self, source)
    108         self.reset()
    109         self._cont_handler.setDocumentLocator(ExpatLocator(self))
--> 110         xmlreader.IncrementalParser.parse(self, source)
    111 
    112     def prepareParser(self, source):

/Users/amicol/anaconda/lib/python3.6/xml/sax/xmlreader.py in parse(self, source)
    123         buffer = file.read(self._bufsize)
    124         while buffer:
--> 125             self.feed(buffer)
    126             buffer = file.read(self._bufsize)
    127         self.close()

/Users/amicol/anaconda/lib/python3.6/xml/sax/expatreader.py in feed(self, data, isFinal)
    208             # document. When feeding chunks, they are not normally final -
    209             # except when invoked from close.
--> 210             self._parser.Parse(data, isFinal)
    211         except expat.error as e:
    212             exc = SAXParseException(expat.ErrorString(e.code), e, self)

/Users/ilan/minonda/conda-bld/python-3.6_1494525719021/work/Python-3.6.1/Modules/pyexpat.c in EndElement()

/Users/amicol/anaconda/lib/python3.6/xml/sax/expatreader.py in end_element(self, name)
    323 
    324     def end_element(self, name):
--> 325         self._cont_handler.endElement(name)
    326 
    327     def start_element_ns(self, name, attrs):

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/tools/plainxml.py in endElement(self, name, suppress)
    199                 if hasattr(self.realHandler, "_end_%s"%name):
    200 			res = getattr(self.realHandler,
--> 201 				"_end_%s"%name)(name, attrs, contents)
    202                 elif hasattr(self, "_defaultEnd"):
    203                         res = self._defaultEnd(name, attrs, contents)

/Users/amicol/anaconda/lib/python3.6/site-packages/pyvo/tools/uws.py in _end_destruction(self, name, attrs, content)
     37         def _end_destruction(self, name, attrs, content):
     38 		time = Time(
---> 39 			content.strip(), format="isot")
     40                 self.job["destruction"] = time.datetime
     41 

/Users/amicol/anaconda/lib/python3.6/site-packages/astropy/time/core.py in __init__(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
    282         else:
    283             self._init_from_vals(val, val2, format, scale, copy,
--> 284                                  precision, in_subfmt, out_subfmt)
    285 
    286         if self.location and (self.location.size > 1 and

/Users/amicol/anaconda/lib/python3.6/site-packages/astropy/time/core.py in _init_from_vals(self, val, val2, format, scale, copy, precision, in_subfmt, out_subfmt)
    332         # Parse / convert input values into internal jd1, jd2 based on format
    333         self._time = self._get_time_fmt(val, val2, format, scale,
--> 334                                         precision, in_subfmt, out_subfmt)
    335         self._format = self._time.name
    336 

/Users/amicol/anaconda/lib/python3.6/site-packages/astropy/time/core.py in _get_time_fmt(self, val, val2, format, scale, precision, in_subfmt, out_subfmt)
    376                 pass
    377         else:
--> 378             raise ValueError('Input values did not match {0}'.format(err_msg))
    379 
    380     @classmethod

ValueError: Input values did not match the format class isot

**Comment by funbaker** [comment]
Fixed in https://github.com/pyvirtobs/pyvo/commit/f757d60da3fd93ed71a4cfa176e725d4262034f7

Will do a pypi release soon.
