### ISSUE TITLE
Add preferred citation

### ISSUE THREAD

**Issue by bsipocz** [pyvirtobs/pyvo#95]
Please add the preferred citation somewhere to the documentation (and preferable also to a CITATION file)

**Comment by funbaker** [comment]
I'm onto it, gonna make a submission to the ASCL.

**Comment by bsipocz** [comment]
Thanks. If you like, a zenodo entry may be easier to make and they provide DOI, too.

**Comment by funbaker** [comment]
Zenodo entry is created, doi is coming with the next release...

**Comment by bsipocz** [comment]
Thanks. Is there a bibtex entry already or that's due to come with the next release, too? (I'm asking as I would like to cite all the affiliated packages in the astropy paper).

**Comment by funbaker** [comment]
If it's very urgent, theres an old entry available here: https://ascl.net/1402.004
The newly submitted entry is here https://ascl.net/code/v/1888

On zenodo, i cannot see an option to create entries from old releases, and the README text is not suitable as abstract yet anyway.

**Comment by augustfly** [comment]
I'd also advise putting it in the top level github readme. We think that has the best first look discoverability for an author wishing to cite the code.

**Comment by funbaker** [comment]
Added a zenodo badge in README.rst
